### ISSUE TITLE
Unable to flash bootloader from Arduino IDE

### ISSUE THREAD

**Issue by dlabun** [sparkfun/SAMD21_Dev_Breakout#3]
With v1.2.1 of the SAMD21 core you cannot flash the bootloader from the Arduino IDE. The IDE is looking for the BIN file with the name "samd21_sam_ba.bin" when the file is actually named "samd21_sam_ba_sparkfun.bin"

**Comment by ToniCorinne** [comment]
@jimblom can you see if this is still an issue? Thanks!

**Comment by jimblom** [comment]
Shoot, looks like I forgot to close this issue out earlier.

"Burn bootloader" for SAMD21 Dev and Mini boards was fixed in the SparkFun SAMD core version 1.3.0. Verified that it works on the current version - 1.3.2.
